// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Maintainer",
            "email": "your@email.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Health check and list of registered providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Gateway Health",
                "responses": {
                    "200": {
                        "description": "status: ok, providers: list",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns an aggregated summary of gateway usage, including requests, errors, tokens, and latency by provider/model.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Get gateway metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.MetricsSummary"
                        }
                    }
                }
            }
        },
        "/metrics/dashboard": {
            "get": {
                "description": "Returns the self-contained HTML/JS monitoring dashboard.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Metrics dashboard",
                "responses": {
                    "200": {
                        "description": "HTML Dashboard",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics/reset": {
            "post": {
                "description": "Clears all in-memory metrics counters and buffers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Reset gateway metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/providers": {
            "get": {
                "description": "Returns all registered providers with config and ready status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "List providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/httptransport.ProviderInfo"
                            }
                        }
                    }
                }
            }
        },
        "/tokenize": {
            "post": {
                "description": "Tokenize string text using tiktoken (cl100k_base) and return stats",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utilities"
                ],
                "summary": "Tokenize text",
                "parameters": [
                    {
                        "description": "Text to tokenize",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TokenizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TokenizeResponse"
                        }
                    }
                }
            }
        },
        "/v1/chat/completions": {
            "post": {
                "description": "Entry point for the AI Gateway's chat completion interface (OpenAI compatible).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "completions"
                ],
                "summary": "Chat completions",
                "parameters": [
                    {
                        "description": "Chat Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "405": {
                        "description": "method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/embeddings": {
            "post": {
                "description": "Vector generation endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "embeddings"
                ],
                "summary": "Embeddings",
                "parameters": [
                    {
                        "description": "Embedding Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EmbeddingRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Provider name override",
                        "name": "X-AI-Provider",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.EmbeddingResponse"
                        }
                    }
                }
            }
        },
        "/v1/messages": {
            "post": {
                "description": "Anthropic-compatible messages endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "completions"
                ],
                "summary": "Anthropic Messages",
                "parameters": [
                    {
                        "description": "Anthropic Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/anthropic.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/anthropic.Response"
                        }
                    }
                }
            }
        },
        "/v1/models/{provider}": {
            "get": {
                "description": "List available capabilities/models for a provider.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "List models",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name (e.g., openai, anthropic)",
                        "name": "provider",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Provider name if not in path",
                        "name": "X-AI-Provider",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/usage": {
            "get": {
                "description": "Get usage statistics for a specific provider.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usage"
                ],
                "summary": "Usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name override",
                        "name": "X-AI-Provider",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Usage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "anthropic.Content": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "for tool_result",
                    "type": "string"
                },
                "id": {
                    "description": "for tool_use",
                    "type": "string"
                },
                "input": {
                    "description": "for tool_use"
                },
                "is_error": {
                    "description": "for tool_result",
                    "type": "boolean"
                },
                "name": {
                    "description": "for tool_use",
                    "type": "string"
                },
                "text": {
                    "description": "for text",
                    "type": "string"
                },
                "tool_use_id": {
                    "description": "for tool_result",
                    "type": "string"
                },
                "type": {
                    "description": "\"text\", \"tool_use\", or \"tool_result\"",
                    "type": "string"
                }
            }
        },
        "anthropic.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Can be string or []Content"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "anthropic.Request": {
            "type": "object",
            "properties": {
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/anthropic.Message"
                    }
                },
                "model": {
                    "type": "string"
                },
                "stop_sequences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stream": {
                    "type": "boolean"
                },
                "system": {},
                "temperature": {
                    "type": "number"
                },
                "tool_choice": {},
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/anthropic.Tool"
                    }
                },
                "top_p": {
                    "type": "number"
                }
            }
        },
        "anthropic.Response": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/anthropic.Content"
                    }
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "role": {
                    "description": "\"assistant\"",
                    "type": "string"
                },
                "stop_reason": {
                    "type": "string"
                },
                "stop_sequence": {
                    "type": "string"
                },
                "type": {
                    "description": "\"message\"",
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/anthropic.Usage"
                }
            }
        },
        "anthropic.Tool": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "input_schema": {},
                "name": {
                    "type": "string"
                }
            }
        },
        "anthropic.Usage": {
            "type": "object",
            "properties": {
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                }
            }
        },
        "domain.ChatDelta": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ToolCallChunk"
                    }
                }
            }
        },
        "domain.ChatRequest": {
            "type": "object",
            "properties": {
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Message"
                    }
                },
                "model": {
                    "type": "string"
                },
                "n": {
                    "type": "integer"
                },
                "stop": {},
                "stream": {
                    "type": "boolean"
                },
                "stream_options": {
                    "$ref": "#/definitions/domain.StreamOptions"
                },
                "temperature": {
                    "type": "number"
                },
                "tool_choice": {},
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Tool"
                    }
                },
                "top_p": {
                    "type": "number"
                }
            }
        },
        "domain.ChatResponse": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Choice"
                    }
                },
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/domain.Usage"
                }
            }
        },
        "domain.Choice": {
            "type": "object",
            "properties": {
                "delta": {
                    "$ref": "#/definitions/domain.ChatDelta"
                },
                "finish_reason": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "message": {
                    "$ref": "#/definitions/domain.Message"
                }
            }
        },
        "domain.EmbeddingData": {
            "type": "object",
            "properties": {
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "domain.EmbeddingRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "description": "Can be string or []string"
                },
                "model": {
                    "type": "string",
                    "example": "text-embedding-3-small"
                }
            }
        },
        "domain.EmbeddingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.EmbeddingData"
                    }
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/domain.Usage"
                }
            }
        },
        "domain.FunctionCall": {
            "type": "object",
            "properties": {
                "arguments": {
                    "description": "JSON string",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.FunctionChunk": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.FunctionDefinition": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "description": "JSON Schema"
                }
            }
        },
        "domain.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "description": "\"system\" | \"user\" | \"assistant\" | \"tool\"",
                    "type": "string"
                },
                "tool_call_id": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ToolCall"
                    }
                }
            }
        },
        "domain.MetricsSummary": {
            "type": "object",
            "properties": {
                "avg_duration_ms": {
                    "type": "number"
                },
                "by_model": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.RouteStats"
                    }
                },
                "by_provider": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.RouteStats"
                    }
                },
                "by_route": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.RouteStats"
                    }
                },
                "recent_requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RequestSnapshot"
                    }
                },
                "time_series": {
                    "$ref": "#/definitions/domain.TimeSeriesUsage"
                },
                "total_errors": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                },
                "uptime_secs": {
                    "type": "integer"
                }
            }
        },
        "domain.RequestSnapshot": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "route": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "domain.RouteStats": {
            "type": "object",
            "properties": {
                "avg_duration_ms": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "errors": {
                    "type": "integer"
                },
                "p95_duration_ms": {
                    "type": "integer"
                },
                "total_completion_tokens": {
                    "type": "integer"
                },
                "total_prompt_tokens": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "domain.StreamOptions": {
            "type": "object",
            "properties": {
                "include_usage": {
                    "type": "boolean"
                }
            }
        },
        "domain.TimeSeriesUsage": {
            "type": "object",
            "properties": {
                "daily": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.UsagePoint"
                    }
                },
                "monthly": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.UsagePoint"
                    }
                },
                "weekly": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.UsagePoint"
                    }
                }
            }
        },
        "domain.TokenizeRequest": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "example": "Hello, world!"
                }
            }
        },
        "domain.TokenizeResponse": {
            "type": "object",
            "properties": {
                "stats": {
                    "$ref": "#/definitions/domain.TokenizeStats"
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.TokenizeStats": {
            "type": "object",
            "properties": {
                "byte_count": {
                    "type": "integer"
                },
                "character_count": {
                    "type": "integer"
                },
                "token_count": {
                    "type": "integer"
                }
            }
        },
        "domain.Tool": {
            "type": "object",
            "properties": {
                "function": {
                    "$ref": "#/definitions/domain.FunctionDefinition"
                },
                "type": {
                    "description": "always \"function\"",
                    "type": "string"
                }
            }
        },
        "domain.ToolCall": {
            "type": "object",
            "properties": {
                "function": {
                    "$ref": "#/definitions/domain.FunctionCall"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "description": "always \"function\"",
                    "type": "string"
                }
            }
        },
        "domain.ToolCallChunk": {
            "type": "object",
            "properties": {
                "function": {
                    "$ref": "#/definitions/domain.FunctionChunk"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.Usage": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "domain.UsagePoint": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "e.g. \"2024-04-15\"",
                    "type": "string"
                },
                "tokens": {
                    "type": "integer"
                }
            }
        },
        "httptransport.ProviderInfo": {
            "type": "object",
            "properties": {
                "configured": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "ready": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AI Gateway API",
	Description:      "Multi-provider AI Gateway. Proxies requests to OpenAI, Anthropic, GitHub Copilot, Ollama, Bedrock.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
