import { TransactionCategory, TransactionCategoryMetadata } from './types';

export const TRANSACTION_CATEGORIES: Record<TransactionCategory, TransactionCategoryMetadata> = {
  groceries: {
    id: 'groceries',
    label: 'Groceries',
    icon: 'shopping-cart',
    color: 'bg-green-500',
    type: 'expense',
    description: 'Food and grocery store purchases',
  },
  restaurants: {
    id: 'restaurants',
    label: 'Restaurants & Dining',
    icon: 'utensils',
    color: 'bg-orange-500',
    type: 'expense',
    description: 'Dining out, takeout, and food delivery',
  },
  fuel: {
    id: 'fuel',
    label: 'Fuel',
    icon: 'fuel',
    color: 'bg-yellow-600',
    type: 'expense',
    description: 'Gasoline and fuel purchases',
  },
  parking: {
    id: 'parking',
    label: 'Parking',
    icon: 'square',
    color: 'bg-slate-500',
    type: 'expense',
    description: 'Parking fees and tolls',
  },
  insurance: {
    id: 'insurance',
    label: 'Insurance',
    icon: 'shield',
    color: 'bg-blue-600',
    type: 'expense',
    description: 'Insurance premiums (health, auto, home)',
  },
  utilities: {
    id: 'utilities',
    label: 'Utilities',
    icon: 'lightbulb',
    color: 'bg-amber-500',
    type: 'expense',
    description: 'Electricity, water, gas, waste',
  },
  rent: {
    id: 'rent',
    label: 'Rent',
    icon: 'home',
    color: 'bg-red-600',
    type: 'expense',
    description: 'Rental payments',
  },
  mortgage: {
    id: 'mortgage',
    label: 'Mortgage',
    icon: 'building',
    color: 'bg-red-700',
    type: 'expense',
    description: 'Mortgage payments',
  },
  phone: {
    id: 'phone',
    label: 'Phone',
    icon: 'phone',
    color: 'bg-indigo-500',
    type: 'expense',
    description: 'Mobile phone service',
  },
  internet: {
    id: 'internet',
    label: 'Internet',
    icon: 'wifi',
    color: 'bg-cyan-500',
    type: 'expense',
    description: 'Internet service provider',
  },
  subscriptions: {
    id: 'subscriptions',
    label: 'Subscriptions',
    icon: 'repeat',
    color: 'bg-purple-500',
    type: 'expense',
    description: 'Recurring subscription services',
  },
  gym: {
    id: 'gym',
    label: 'Gym & Fitness',
    icon: 'dumbbell',
    color: 'bg-pink-500',
    type: 'expense',
    description: 'Gym membership and fitness classes',
  },
  medical: {
    id: 'medical',
    label: 'Medical',
    icon: 'heart',
    color: 'bg-rose-500',
    type: 'expense',
    description: 'Doctor visits and medical services',
  },
  pharmacy: {
    id: 'pharmacy',
    label: 'Pharmacy',
    icon: 'pill',
    color: 'bg-teal-500',
    type: 'expense',
    description: 'Medications and pharmaceutical purchases',
  },
  entertainment: {
    id: 'entertainment',
    label: 'Entertainment',
    icon: 'film',
    color: 'bg-fuchsia-500',
    type: 'expense',
    description: 'Movies, concerts, games, hobbies',
  },
  travel: {
    id: 'travel',
    label: 'Travel',
    icon: 'plane',
    color: 'bg-sky-500',
    type: 'expense',
    description: 'Flights, hotels, vacation expenses',
  },
  shopping: {
    id: 'shopping',
    label: 'Shopping',
    icon: 'shopping-bag',
    color: 'bg-pink-600',
    type: 'expense',
    description: 'Retail and clothing purchases',
  },
  gifts: {
    id: 'gifts',
    label: 'Gifts',
    icon: 'gift',
    color: 'bg-red-500',
    type: 'expense',
    description: 'Gifts and charitable giving',
  },
  charity: {
    id: 'charity',
    label: 'Charity',
    icon: 'heart-handshake',
    color: 'bg-lime-500',
    type: 'expense',
    description: 'Charitable donations and contributions',
  },
  education: {
    id: 'education',
    label: 'Education',
    icon: 'book-open',
    color: 'bg-indigo-600',
    type: 'expense',
    description: 'Tuition, courses, and educational materials',
  },
  books: {
    id: 'books',
    label: 'Books',
    icon: 'book',
    color: 'bg-amber-700',
    type: 'expense',
    description: 'Book purchases',
  },
  salary: {
    id: 'salary',
    label: 'Salary',
    icon: 'briefcase',
    color: 'bg-emerald-600',
    type: 'income',
    description: 'Salary and regular employment income',
  },
  bonus: {
    id: 'bonus',
    label: 'Bonus',
    icon: 'star',
    color: 'bg-yellow-500',
    type: 'income',
    description: 'Bonuses and incentive payments',
  },
  'investment income': {
    id: 'investment income',
    label: 'Investment Income',
    icon: 'trending-up',
    color: 'bg-green-600',
    type: 'income',
    description: 'Dividends, interest, and investment returns',
  },
  refund: {
    id: 'refund',
    label: 'Refund',
    icon: 'arrow-left',
    color: 'bg-blue-500',
    type: 'income',
    description: 'Refunds and reversals',
  },
  transfer: {
    id: 'transfer',
    label: 'Transfer',
    icon: 'arrow-right-left',
    color: 'bg-gray-500',
    type: 'non-budget',
    description: 'Transfers between accounts',
  },
  fee: {
    id: 'fee',
    label: 'Fee',
    icon: 'zap',
    color: 'bg-red-600',
    type: 'expense',
    description: 'Bank fees and service charges',
  },
  interest: {
    id: 'interest',
    label: 'Interest',
    icon: 'percent',
    color: 'bg-green-400',
    type: 'income',
    description: 'Interest earned on deposits',
  },
  tax: {
    id: 'tax',
    label: 'Tax',
    icon: 'receipt',
    color: 'bg-orange-700',
    type: 'expense',
    description: 'Tax payments and withholding',
  },
  other: {
    id: 'other',
    label: 'Other',
    icon: 'help-circle',
    color: 'bg-gray-400',
    type: 'non-budget',
    description: 'Uncategorized transactions',
  },
};
