import { CategoryTaggingRule } from './types';

export const CATEGORY_TAGGING_RULES: CategoryTaggingRule[] = [
  {
    category: 'groceries',
    keywords: [
      'grocery',
      'supermarket',
      'whole foods',
      'trader joe',
      'safeway',
      'kroger',
      'walmart',
      'costco',
      'market',
    ],
    merchants: ['WHOLE FOODS', 'TRADER JOE', 'SAFEWAY', 'KROGER', 'COSTCO'],
    autoTag: true,
  },
  {
    category: 'restaurants',
    keywords: ['restaurant', 'dining', 'cafe', 'coffee', 'pizza', 'burger', 'taco', 'sushi', 'ramen'],
    merchants: ['DOORDASH', 'UBER EATS', 'GRUBHUB', 'FOODPANDA'],
    autoTag: true,
  },
  {
    category: 'fuel',
    keywords: ['gas', 'fuel', 'chevron', 'shell', 'chevron', 'bp', 'exxon', 'mobil'],
    merchants: ['CHEVRON', 'SHELL', 'BP', 'EXXON', 'MOBIL'],
    autoTag: true,
  },
  {
    category: 'parking',
    keywords: ['parking', 'valet', 'toll', 'meter'],
    merchants: ['PARKWHIZ', 'SPOTHERO', 'PARKINGPANDA'],
    autoTag: true,
  },
  {
    category: 'insurance',
    keywords: ['insurance', 'premium', 'geico', 'state farm', 'allstate'],
    merchants: ['GEICO', 'STATE FARM', 'ALLSTATE'],
    autoTag: false,
  },
  {
    category: 'utilities',
    keywords: ['electricity', 'water', 'gas', 'utility', 'pg&e', 'consolidated edison'],
    merchants: ['PG&E', 'CON EDISON', 'DWP'],
    autoTag: true,
  },
  {
    category: 'rent',
    keywords: ['rent', 'rental payment', 'lease'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'mortgage',
    keywords: ['mortgage', 'home loan', 'principal', 'interest payment'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'phone',
    keywords: ['phone', 'mobile', 'verizon', 'at&t', 't-mobile', 'sprint'],
    merchants: ['VERIZON', 'AT&T', 'T-MOBILE', 'SPRINT'],
    autoTag: true,
  },
  {
    category: 'internet',
    keywords: ['internet', 'isp', 'broadband', 'comcast', 'verizon fios', 'spectrum'],
    merchants: ['COMCAST', 'VERIZON FIOS', 'SPECTRUM'],
    autoTag: true,
  },
  {
    category: 'subscriptions',
    keywords: ['subscription', 'annual', 'monthly', 'netflix', 'spotify', 'adobe', 'microsoft'],
    merchants: ['NETFLIX', 'SPOTIFY', 'ADOBE', 'MICROSOFT'],
    autoTag: true,
  },
  {
    category: 'gym',
    keywords: ['gym', 'fitness', 'yoga', 'peloton', 'lululemon'],
    merchants: ['PELOTON', 'LULULEMON', 'EQUINOX'],
    autoTag: true,
  },
  {
    category: 'medical',
    keywords: ['doctor', 'hospital', 'medical', 'clinic', 'surgeon'],
    merchants: ['KAISER', 'CEDARS SINAI', 'MOUNT SINAI'],
    autoTag: false,
  },
  {
    category: 'pharmacy',
    keywords: ['pharmacy', 'cvs', 'walgreens', 'medicine', 'prescripti'],
    merchants: ['CVS', 'WALGREENS', 'RITE AID'],
    autoTag: true,
  },
  {
    category: 'entertainment',
    keywords: ['movie', 'theater', 'concert', 'ticket', 'game', 'steam', 'playstation'],
    merchants: ['TICKETMASTER', 'REGAL CINEMA', 'STEAM'],
    autoTag: true,
  },
  {
    category: 'travel',
    keywords: ['airline', 'hotel', 'flight', 'booking', 'expedia', 'airbnb'],
    merchants: ['UNITED AIRLINES', 'MARRIOTT', 'AIRBNB', 'BOOKING.COM'],
    autoTag: true,
  },
  {
    category: 'shopping',
    keywords: ['amazon', 'ebay', 'mall', 'retail', 'clothing', 'apparel', 'fashion'],
    merchants: ['AMAZON', 'EBAY', 'TARGET', 'MACY'],
    autoTag: true,
  },
  {
    category: 'gifts',
    keywords: ['gift', 'present', 'birthday', 'anniversary'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'charity',
    keywords: ['donation', 'charity', 'nonprofit', 'relief', 'foundation'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'education',
    keywords: ['tuition', 'course', 'university', 'college', 'school', 'udemy', 'coursera'],
    merchants: ['UDEMY', 'COURSERA', 'MASTERCLASS'],
    autoTag: true,
  },
  {
    category: 'books',
    keywords: ['book', 'kindle', 'audible'],
    merchants: ['AMAZON BOOKS', 'BARNES NOBLE', 'AUDIBLE'],
    autoTag: true,
  },
  {
    category: 'salary',
    keywords: ['salary', 'payroll', 'wage', 'direct deposit'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'bonus',
    keywords: ['bonus', 'incentive', 'commission'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'investment income',
    keywords: ['dividend', 'investment', 'interest income', 'capital gains'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'refund',
    keywords: ['refund', 'credit', 'reversal', 'return'],
    merchants: [],
    autoTag: true,
  },
  {
    category: 'transfer',
    keywords: ['transfer', 'xfer', 'payment'],
    merchants: [],
    autoTag: false,
  },
  {
    category: 'fee',
    keywords: ['fee', 'charge', 'overdraft', 'atm'],
    merchants: [],
    autoTag: true,
  },
  {
    category: 'interest',
    keywords: ['interest earned', 'interest paid', 'yield'],
    merchants: [],
    autoTag: true,
  },
  {
    category: 'tax',
    keywords: ['tax', 'irs', 'withholding', 'estimated tax'],
    merchants: [],
    autoTag: false,
  },
];
