name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: node
    steps:
      - name: Semantic Release Action
        uses: codfish/semantic-release-action@v1
  
          
